// <auto-generated />
namespace BTL_QLBQA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addcreateattableorder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcreateattableorder));
        
        string IMigrationMetadata.Id
        {
            get { return "202308291601458_add-create-at-table-order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
